### ISSUE TITLE
RubyMotion の Atom パッケージを作ってみた

### ISSUE THREAD

**Issue by satococoa** [GitHubKaigi/2014-LT-Application#10]
GitHub が開発した [Atom エディタ](https://atom.io/) の [RubyMotion Package](https://atom.io/packages/RubyMotion) を作ったのでその話をしたいと思います。

RubyMotion Package 自体の実装の詳細に触れるよりは、Atom パッケージの作り方の基本〜ハマったところなどをさらっと紹介するつもりです。

クレジット: 海老沢 聡 (@satococoa)

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!
