### ISSUE TITLE
How to workaround the limit to the number of private repos

### ISSUE THREAD

**Issue by yuryu** [GitHubKaigi/2014-LT-Application#11]
## 内容

I would like to talk about how to reduce the number of paid private repositories in your organization.

When you use private repositories in your organization, everyone wants to make and use their own repositories. It is a good practice to keep repositories small. However, GitHub costs more as the number of private repos increases unlike GitHub Enterprise.

As forked repositories don't count towards the limit, making a single private repo and fork reduces the number of private repos in a organization. Git-subtree helps to split such repos after some development.
## サイトへ掲載する際のクレジット

Haruka Iwao, FreakOut, Inc.

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!
