### ISSUE TITLE
継続的飲み会インテグレーション

### ISSUE THREAD

**Issue by shokai** [GitHubKaigi/2014-LT-Application#13]
# 概要

GitHubを使ったテスト駆動スケジュール調整により、半年ぶりの飲み会が無事開催できました。技術者は面倒くさがりなのでなかなか予定を書いてくれませんが、通らないテストを見ると気持ち悪がって書いてくれました。issueやpull requestも便利でした。
# クレジット

@shokai at アレ会

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!
