### ISSUE TITLE
時差を超えしPullRequest

### ISSUE THREAD

**Issue by mocyuto** [GitHubKaigi/2014-LT-Application#14]
"PullRequestによる開発は、時差・国境をも超える。"

現在弊社はオフィスが日本とUSにあり、自分はUSのチームメイトと開発を進めています。
地理的制約や時差、開発のコミュニケーションが困難になる中、Githubを使うことで国を超えたチーム開発をスムーズに行います。
## 所属

株式会社CyberZ  @moc-yuto

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!
