### ISSUE TITLE
ハイサイ! 南の島 Okinawa でも enjoy GitHub !

### ISSUE THREAD

**Issue by yutakakinjyo** [GitHubKaigi/2014-LT-Application#15]
# 内容

みなさん、沖縄のイメージどうですか？ 瓦屋の家に、石畳の道に、水牛が歩いてるイメージですか？

のん！

コンクリート製ですよ！、車社会ですよ！、ネット繋がりますよ！ そう GitHub だってできるんです！

沖縄に本社を構える OCC でまさに今,　全社的に GitHub の導入を進めています
目指す所は開発だけでなく、業務のインフラとして活用することです。
- 社内で GitHub を流行らせるために 「GitHub おじさん」を名乗った話
- そしたら「おじさん」が増えた話
- 新人研修の教材管理に使用した話
- 少しずつ使う人が増えた話
- 会社導入において、困っている話

これから周りに広めていきたい、会社で使いたいと思われてる方に、参考になると思います！(仲間が欲しい!)
# クレジット

株式会社 OCC 金城裕

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!
