### ISSUE TITLE
Lita レビュアーおみくじ

### ISSUE THREAD

**Issue by fukayatsu** [GitHubKaigi/2014-LT-Application#17]
#12 がよさそうだったので、[jimmycuadra/lita](https://github.com/jimmycuadra/lita)版を作りました。

> [fukayatsu/lita-reviewer-lotto](https://github.com/fukayatsu/lita-reviewer-lotto)

Piece of Cake, Inc.では基本的にGithub flowで開発しており、デプロイもpull-requestマージ後にLitaを使ってデプロイしています。
# 

クレジット: Atsuo Fukaya / @fukayatsu
Piece of Cake, Inc.

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!

**Comment by fukayatsu** [comment]
了解ですー :)
