### ISSUE TITLE
Trendingを制覇せよ！OSSのライブラリのマーケティング

### ISSUE THREAD

**Issue by modocache** [GitHubKaigi/2014-LT-Application#2]
## 内容

> せっかく公開したオープンソース、人に使ってもらいたい！
> 
> 人に車輪の再発明をやめて自分のライブラリを使ってもらいたい！

そう思ったことはありませんか？

オープンソースは、たくさんの人に使ってもらってこそコードの品質が向上するし、世の中のためにもなります。本LTでは、自分のコードをどうマーケティングすればより多くの人に使ってもらえるのかについて話します。
## サイトに掲載する際のクレジット

Brian Gesiak（東京大学大学院）

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!

**Comment by modocache** [comment]
![](http://37.media.tumblr.com/tumblr_m32lku6i721r9kmt5o1_400.gif)
