### ISSUE TITLE
新たなるソーシャルコーディング時代の幕開け

### ISSUE THREAD

**Issue by kenchan** [GitHubKaigi/2014-LT-Application#22]
2年前、受託開発企業におけるGitHubの導入とソーシャルコーディングという文化の効果について発表しました。

https://speakerdeck.com/kenchan/social-coding

この2年で状況は大きく変わり、GitHub(やGitHub:E)をオフィシャルなリポジトリとして利用している企業は増加の一途をたどっています。

その中で、受託開発を生業としている企業が挑戦している、GitHubを活用した新しい取り組みについて発表します。

所属：株式会社 永和システムマネジメント
名前：高橋健一
ID: kenchan
(キャンセル待ちリストの2番目に登録されています。)

**Comment by naoya** [comment]
本セッション、当選しました。当日よろしくお願いします。

**Comment by kenchan** [comment]
ありがとうございます！当日宜しくお願いします！
