### ISSUE TITLE
Gitを使えないあの子にもPull Requestを送ってもらう方法

### ISSUE THREAD

**Issue by awakia** [GitHubKaigi/2014-LT-Application#3]
## 簡単な内容の紹介

ワーディングやボタンの色一つで、コンバージョン率が変わると証明されてしまった世の中。
会社で日に日に増える、ビジネスサイドからの「相川さん、ここの文言XXXに変えてもらえませんか？」という声。
そんな、彼ら彼女らに声でなくPull Requestを届けてもらうことを夢見た話。
### サイトに掲載する際のお名前

相川直視
### 所属

Wantedly

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!
