### ISSUE TITLE
GitBucketがGithubクローンすぎる件

### ISSUE THREAD

**Issue by takezoe** [GitHubKaigi/2014-LT-Application#5]
## 内容

私たちはオープンソースのGithubクローン「[GitBucket](https://github.com/takezoe/gitbucket)」を開発しています。GitBucketがいかに簡単に導入でき、Githubの機能を忠実に再現しているかについて紹介させていただきたいと思います。
## クレジット

竹添直樹、島本多可子
BizReach,Inc.

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!
