### ISSUE TITLE
デザイナーにOctcatのこと教えたらPull Requestまでできるようになっちゃった話。

### ISSUE THREAD

**Issue by kozyty** [GitHubKaigi/2014-LT-Application#7]
## 内容

Octcatかわいいですよね。でもgitとかGithubとか怖がっている方って多いじゃないですか。今回は最初怖がっていたのにプルリクまでできるようになっちゃった話をしたいと思います。

前半はネタみたいなものですが、後半は「運用フローがGithubで完結する利点」といった真面目な内容も含めて話してみたいと思います。

※気づいたらイベントキャンセル待ち135人目だったので、このLT参加に命かけてますｗ

どうぞよろしくお願い致します！！
## クレジット

株式会社nanapi　こじてぃ

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!
