### ISSUE TITLE
GitHubを使って自分の人生を管理している話

### ISSUE THREAD

**Issue by kubosho** [GitHubKaigi/2014-LT-Application#8]
日々生きていく中で、いろいろと忘れてしまうことがありました。

そこで、普段使っているGitHub上で自分の人生を管理するようにした話をします。GitHub上で人生を管理するようにした効能や改善点を話そうと思います。

該当リポジトリ: [kubosho/mylife](https://github.com/kubosho/mylife)
## クレジット

株式会社グラニ 久保田翔太(@kubosho_)

**Comment by naoya** [comment]
残念ながら見送りとなりました。次回開催は未定ですが、またの機会によろしくお願いします!
